### ISSUE TITLE
darkroom--leave doesn't check for tentative-mode and one-window situation

### ISSUE THREAD

**Issue by levitanong** [joaotavora/darkroom#10]
Repeatedly toggling `darkroom-tentative-mode` when buffer is not the only open window triggers `text-scale-decrease`, without corresponding `text-scale-increase`, causing an unbounded decrease in text size.

https://github.com/joaotavora/darkroom/blob/master/darkroom.el#L307

**Comment by joaotavora** [comment]
Oh, that explains some buggy behaviour I had been seeing.  Do you have a (relatively simple) solution you want to suggest?

**Comment by levitanong** [comment]
Off the top of my head, store in some variable like `text-scale-increased-p` which becomes `t` when scale has been increased at some point, and only `text-scale-decrease` if this variable is `t`. If this is acceptable to you, I can make a PR.

**Comment by levitanong** [comment]
Found an even cleaner fix: just set `(text-scale-mode -1)`.
