### ISSUE TITLE
Missing autoloads for darkroom

### ISSUE THREAD

**Issue by luismbo** [joaotavora/darkroom#6]
I would be nice if `darkroom-mode` and `darkroom-tentative-mode` had autoloads pre-defined.

**Comment by cjauvin** [comment]
I agree, it's confusing if you install it via Melpa, as you expect it to be available right away after install.

**Comment by luismbo** [comment]
Looks like the autoload cookies were added long ago (https://github.com/joaotavora/darkroom/commit/9709dbdc3771fa13c407073392d3a8c7b074704b), but the ELPA package hasn't been updated since Dec 2014.

**Comment by joaotavora** [comment]
> Looks like the autoload cookies were added long ago (9709dbd), but the ELPA package hasn't been updated since Dec 2014.

Thanks for reporting.  Got to remember how to do that again, it's somewhere in the ELPA instructions...

**Comment by joaotavora** [comment]
I fixed this the other day. https://elpa.gnu.org/packages/darkroom.html
